#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

current_remote="$1"
current_branch=$(git branch --show-current)

function check_branch_and_remote(){
    protected_branch="$1"
    protected_remote="$2"

    if [ "$current_remote" = "$protected_remote" ] && [ "$current_branch" = "protected_branch" ]
    then
        echo >&2 "Pushing \'$protected_branch\' branch to \
                  \'$protected_remote\' remote is not allowed. \
                  (pre-push hook)"
        exit 1
    fi
}

# Don't push 'public' branch to 'private' remote
check_branch_and_remote public private

# Don't push 'private' branch to 'public' remote
check_branch_and_remote private public
